# frozen_string_literal: true

source 'https://rubygems.org'

gem 'annotate'
gem 'bcrypt'
gem 'jquery-rails'
gem 'mysql2', '0.3.20'
gem 'rails', '3.2.22.5'
gem 'test-unit', '~> 3.0'
gem 'ckeditor', '4.1.3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'bootstrap-sass', '3.1.1.0'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'sass-rails',   '~> 3.2.3'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'pry'
  gem 'rubocop', require: false
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', require: 'bcrypt'
# To use Jbuilder templates for JSON
# gem 'jbuilder'
# Use unicorn as the app server
# gem 'unicorn'
# Deploy with Capistrano
# gem 'capistrano'
# To use debugger
# gem 'debugger'
ruby '2.3.1'
